api/urls.py
from django.urls import include, path, re_path

from .views import ProductsListView, ProductDetailView, CategoryListView, ProductsByCategoryListView, \
    ProfileDetailView, FavouritesDatailView, FavouritesItemCreateView, FavouritesItemDeleteView, ProfileByUserView, \
        FeedbacksListView, FeedbacksDetailView, OrdersByUserListView, OrdersListView, OrdersDetailView

from .yasg import urlpatterns as docs_urls

urlpatterns = [
    path('catalog/categories/', CategoryListView.as_view()),
    path('catalog/categories/<slug:slug>/', ProductsByCategoryListView.as_view()),
    path('catalog/products/', ProductsListView.as_view()),
    path('catalog/products/<int:pk>/', ProductDetailView.as_view()),
    path('profiles/me/', ProfileByUserView.as_view()),
    path('profiles/<slug:slug>/', ProfileDetailView.as_view()),
    path('profiles/<slug:slug>/orders/', OrdersByUserListView.as_view()),
    path('orders/', OrdersListView.as_view()),
    path('orders/<int:pk>', OrdersDetailView.as_view()),
    path('favourites/', FavouritesItemCreateView.as_view()),
    path('favourites/delete/<int:pk>', FavouritesItemDeleteView.as_view()),
    path('favourites/<slug:slug>/', FavouritesDatailView.as_view()),
    path('feedbacks/', FeedbacksListView.as_view()),
    path('feedbacks/<int:pk>/', FeedbacksDetailView.as_view()),
    path('auth/', include('djoser.urls')),
    path('authenticate/', include('djoser.urls.authtoken')),
]

urlpatterns += docs_urls

catalog/urls.py
from django.urls import path

from .views import GetBrands, GetCategories, GetCategoriesByBrand, GetOneProduct, GetProducts


urlpatterns = [
    path('categories/', GetCategories.as_view(), name='get_categories'),
    path('category/<slug:slug>/', GetProducts.as_view(), name='get_products'),
    path('product/<int:product_id>/', GetOneProduct.as_view(), name='get_product'),
    path('brands/', GetBrands.as_view(), name='get_brands'),
    path('brand/<int:id>/', GetCategoriesByBrand.as_view(), name='get_brand'),
]

ecommerceapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from ecommerceapp.settings import DEBUG, MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', include('main.urls')),
    path('catalog/', include('catalog.urls')),
    path('cart/', include('cart.urls')),
    path('', include('user_product.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),

    path('api/v1/', include('api.urls')),
]

if DEBUG:
    import debug_toolbar

    import mimetypes

    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

catalog/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование товара')
    description = models.TextField(blank=True, verbose_name='Описание товара')
    price = models.IntegerField(verbose_name='Цена товара')
    quantity = models.PositiveIntegerField(
        default=0, verbose_name='Количество товаров')
    quantity_of_purchases = models.PositiveIntegerField(
        default=0, verbose_name='Количество заказов товара')
    image = models.ImageField(
        upload_to='photos/%Y/%m/%d/', blank=True, verbose_name='Изображение товара')
    total_rating = models.DecimalField(
        max_digits=2, decimal_places=1, verbose_name='Общий рейтинг', null=True)
    category = models.ForeignKey(
        'Category', on_delete=models.CASCADE, verbose_name='Категория', related_name='products')
    brand = models.ForeignKey(
        'Brand', on_delete=models.CASCADE, verbose_name='Бренд', related_name='products')

    def __str__(self):
        return self.name

    def get_total_rating(self):
        """Получение итогового рейтинга из отзывов."""
        count_feedback = self.feedbacks.count() if self.feedbacks.count() != 0 else 1
        sum_rating = sum(feedback.rating for feedback in self.feedbacks.all())
        return round(sum_rating/count_feedback, 1)

    def save(self, *args, **kwargs):
        self.total_rating = self.get_total_rating()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['price']


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='images', verbose_name='Товар')
    image = models.ImageField(
        upload_to='products/%Y/%m/%d/', verbose_name='Изображения')

    def __str__(self):
        return str(self.image)


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Категория')
    info = models.TextField(blank=True, verbose_name='Описание категории')
    logo = models.ImageField(
        blank=True, upload_to='logos/%Y/%m/%d/', verbose_name='Лого Категории')

    slug = models.SlugField(max_length=255, unique=True,
                            verbose_name='URL категории')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Brand(models.Model):
    name = models.CharField(max_length=255, verbose_name='Бренд')
    info = models.TextField(blank=True, verbose_name='Описание бренда')
    logo = models.ImageField(
        blank=True, upload_to='logos/%Y/%m/%d/', verbose_name='Лого Бренда')
    category = models.ManyToManyField(
        Category, blank=True, related_name='brands')

    slug = models.SlugField(max_length=255, unique=True,
                            verbose_name='URL бренда')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'


class Feature(models.Model):
    """
    Модель наименования характеристики.
    """
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name='Категория')
    name = models.CharField(max_length=255, verbose_name='Особенность')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Особенность'
        verbose_name_plural = 'Особенности'


class ProductFeature(models.Model):
    """
    Модель значения характеристики.
    """
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT, related_name='features')
    feature = models.ForeignKey(
        Feature, on_delete=models.PROTECT, related_name='features')
    value_float = models.DecimalField(
        blank=True, max_digits=10, decimal_places=1, verbose_name='Значение', null=True)
    value_text = models.TextField(
        blank=True, verbose_name='Значение', null=True)

    def __str__(self):
        return f'{self.feature.name} {self.value_float} {self.value_text}'

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики товаров'

catalog/views.py
from django.views.generic import DetailView, ListView

from .filters import ProductFilter
from .models import Category, Product, Brand, ProductFeature
from user_product.models import Feedback
from cart.forms import CartAddProductForm


class GetCategories(ListView):
    """
    Представление списка 
    """
    model = Category
    template_name = 'catalog/categories.html'
    context_object_name = 'categories'


class GetProducts(ListView):
    """
    Представление списка продуктов одной категории.
    """
    template_name = 'catalog/products.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ProductFilter(
            self.request.GET, queryset=self.get_queryset())
        context['cart_product_form'] = CartAddProductForm()
        context['prev_url'] = self.request.META.get('HTTP_REFERER')
        return context

    def get_queryset(self):
        queryset = Product.objects.filter(category__slug=self.kwargs['slug'])
        return ProductFilter(self.request.GET, queryset=queryset).qs


class GetOneProduct(DetailView):
    """
    Представление информации об одном продукте.
    """
    model = Product
    template_name = 'catalog/product_detail.html'
    pk_url_kwarg = "product_id"

    def get_context_data(self, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['features'] = ProductFeature.objects.filter(
            product__id=self.kwargs['product_id']).select_related('feature')
        context['feedbacks'] = Feedback.objects.filter(
            product__id=self.kwargs['product_id']).select_related('user').prefetch_related('images')
        if self.request.user.is_authenticated:
            feedback_exist = Feedback.objects.filter(
                user=self.request.user, product=self.kwargs['product_id']).exists()
            context['feedback_exists'] = feedback_exist
        context['cart_product_form'] = CartAddProductForm()
        return context


class GetBrands(ListView):
    """
    Представление списка брендов.
    """
    model = Brand
    template_name = 'catalog/brands.html'
    context_object_name = 'brands'


class GetCategoriesByBrand(ListView):
    """
    Представление категорий у одного бренда.
    """
    template_name = 'catalog/categories_by_brand.html'
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(
            brand__id=self.kwargs['id'])
        context['brand'] = Brand.objects.get(id=self.kwargs['id'])
        return context

    def get_queryset(self):
        return Category.objects.filter(brands__id=self.kwargs['id'])

catalog/templates/catalog/brand.html
{% extends 'base.html' %}

{% block title %}
{{ brand.name }}
{% endblock %}

{% block content %}


{% for category in categories %}
<div class="card" style="width: 14em;">
  {% if category.logo %}
  <img src="{{ category.logo.url }}" class="card-img-top">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ category.name }}</h5>
  </div>
  <a href="{% url 'get_products' category.slug %}?brand={{ brand.slug }}" class="stretched-link"></a>
</div>
{% endfor %}

<p>{{ brand.info }}</p>
{% endblock %}

catalog/templates/catalog/brands.html
{% extends 'base.html' %}

{% block title %}
Бренды
{% endblock %}

{% block content %}
{% for brand in brands %}
<div class="d-flex position-relative category">
  {% if brand.logo %}
  <img src="{{ brand.logo.url }}" class="flex-shrink-0 me-3" alt="..." height="60px">
  {% endif %}
  <div>
    <h5 class="mt-0">{{ brand.name }}</h5>
    <a href="{% url 'get_brand' brand.id %}" class="stretched-link"></a>
  </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/categories.html
{% extends 'base.html' %}

{% block title %}
Категории таваров
{% endblock %}

{% block content %}
{% for category in categories %}
<div class="d-flex position-relative category">
  {% if category.logo %}
  <img src="{{ category.logo.url }}" class="flex-shrink-0 me-3" alt="..." width="100px">
  {% endif %}

  <div>
    <h5 class="mt-0">{{ category.name }}</h5>
    <p>{{ category.info }}</p>
    <a href="{% url 'get_products' category.slug %}" class="stretched-link"></a>
  </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/categories_by_brand.html
{% extends 'base.html' %}

{% block title %}
{{ brand.name }}
{% endblock %}

{% block content %}


{% for category in categories %}
<div class="card" style="width: 14em;">
  {% if category.logo %}
  <img src="{{ category.logo.url }}" class="card-img-top">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ category.name }}</h5>
  </div>
  <a href="{% url 'get_products' category.slug %}?brand={{ brand.id }}" class="stretched-link"></a>
</div>
{% endfor %}

<p>{{ brand.info }}</p>
{% endblock %}

catalog/templates/catalog/one_product.html
{% extends 'base.html' %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<div class="product-description">
    {% if product.image %}
    <a href="{{ product.image.url }}"><img src="{{ product.image.url }}" width="400px" alt="..."></a>
    {% endif %}
    <h2 class="name-product">{{ product.name }}</h2>
    <p>{{ product.description }}</p>
    <h3>{{product.price}} руб</h3>
    <p>Бренд: {{ brand.name }}</p>
    <button class="btn btn-primary" type="button">В корзину</button>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Характеристики</th>
                <th scope="col">Значение</th>
            </tr>
        </thead>
        <tbody>
            {% for feature in features %}
            <tr>
                {% if feature.value_float and feature.value_text %}
                <td>{{ feature.feature }}</td>
                <td>{{ feature.value_float }} {{ feature.value_text }}</td>
                {% elif feature.value_float %}
                <td>{{ feature.feature }}</td>
                <td>{{ feature.value_float }}</td>
                {% elif feature.value_text %}
                <td>{{ feature.feature }} </td>
                <td>{{ feature.value_text }}</td>
                {% else %}
                <td>{{ feature.feature }} : -</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock %}

</html>

catalog/templates/catalog/product.html
{% extends 'base.html' %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<div class="product-description">
    {% if product.image %}
    <a href="{{ product.image.url }}"><img src="{{ product.image.url }}" width="400px" alt="..."></a>
    {% endif %}
    <h2 class="name-product">{{ product.name }}</h2>
    <p>{{ product.description }}</p>
    <h3>{{product.price}} руб</h3>
    <p>Бренд: {{ brand.name }}</p>
    <button class="btn btn-primary" type="button">В корзину</button>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Характеристики</th>
                <th scope="col">Значение</th>
            </tr>
        </thead>
        <tbody>
            {% for feature in features %}
            <tr>
                {% if feature.value_float %}
                <td>{{ feature.feature }}</td>
                <td>{{ feature.value_float }}</td>
                {% elif feature.value_text %}
                <td>{{ feature.feature }} </td>
                <td>{{ feature.value_text }}</td>
                {% else %}
                <td>{{ feature.feature }} : -</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock %}

</html>

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<div class="product-description">
    {% if product.image %}
    <a href="{{ product.image.url }}"><img src="{{ product.image.url }}" width="400px" alt="..."></a>
    {% endif %}
    <h2 class="name-product">{{ product.name }}</h2>
    <h5>{{ product.total_rating }} &#9733;</h5>
    <h3>{{product.price}} руб</h3>
    <p>Бренд: {{ product.brand.name }}</p>
    {% if product.quantity %}
    <form action="{% url 'cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ cart_product_form.as_p }}
        <button class="btn btn-primary" type="submit">В корзину</button>
        <a href="{% url 'add_favourites_item' product.id %}" class="btn">В избранное</a>
    </form>
    {% else %}
    <p>НЕТ В НАЛИЧИИ</p>
    {% endif %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Характеристики</th>
                <th scope="col">Значение</th>
            </tr>
        </thead>
        <tbody>
            {% for feature in features %}
            <tr>
                {% if feature.value_float and feature.value_text %}
                <td>{{ feature.feature }}</td>
                <td>{{ feature.value_float }} {{ feature.value_text }}</td>
                {% elif feature.value_float %}
                <td>{{ feature.feature }}</td>
                <td>{{ feature.value_float }}</td>
                {% elif feature.value_text %}
                <td>{{ feature.feature }} </td>
                <td>{{ feature.value_text }}</td>
                {% else %}
                <td>{{ feature.feature }} : -</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <h3>Отзывы о {{ product.name }}</h3>
    <h4>Общий рейтинг: {{ product.total_rating }} &#9733;</h4>
    {% if feedback_exists %}
    <p>Вы уже оставили свой отзыв</p>
    {% else %}

    {% if request.user.is_authenticated %}
    <a href="{% url 'create_feedback' product.id %}" class="btn btn-primary">Написать отзыв</a>
    {% else %}
    <a href="{% url 'login' %}">Войдите, чтобы оставить отзыв</a>
    {% endif %}

    {% endif %}
    {% for feedback in feedbacks %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ feedback.user.username }}</h5>
            <h5 class="card-title"> {{ feedback.rating }} &#9733;</h5>
            <p class="card-text">{{ feedback.text }}</p>
            {% if feedback.images %}
            {% for image in feedback.images.all %}
            <img src="{{ image.image.url }}" alt="" height="100px">
            {% endfor %}
            {% endif %}
        </div>
        <div class="card-footer">
            {{ feedback.created_at}}
            {% if feedback.user == request.user %}
            <a href="{% url 'remove_feedback' feedback.id %}">Удалить</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}

</div>


{% endblock %}

</html>

catalog/templates/catalog/products.html
{% extends 'base.html' %}

{% block title %}
{{ category.name }}
{% endblock %}

{% block content %}

{% comment %}
{% for feature in features %}
{{ feature }}
{% for field in feature.productfeature_set.all.distinct %}
{{ field.value_float }}
{{ field.value_text }}
{% endfor %}
{{ value }}
{% endfor %}
{% endcomment %}

<form action="" method="get">
    {{ filter.form }}
    <button type="submit" class="btn btn-primary">Применить</button>
</form>


{% if products.quantity == 0 %}
<h2>Нет товаров этой категории</h2>
<a href="{{ prev_url }}">Вернуться назад</a>

{% else %}

{% for product in products %}
<div class="card">
    {% if product.image %}
    <a href="{{ product.image.url }}"><img src="{{ product.image.url }}" height="125px" alt="..."></a>
    {% endif %}
    <div class="card-body">
        <a href="{% url 'get_product' product.pk %}">
            <h5 class="card-title">{{ product.name }}</h5>
        </a>
        <p class="card-text">{{ product.total_rating }} &#9733;</p>
        <p class="card-text">Цена: {{ product.price }} Руб</p>
    </div>
    {% if product.quantity %}
    <form action="{% url 'cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ cart_product_form.as_p }}
        <button class="btn btn-primary" type="submit">В корзину</button>
        <a href="{% url 'add_favourites_item' product.id %}" class="btn">В избранное</a>
    </form>
    {% else %}
    <div class="card-footer">
        <span>НЕТ В НАЛИЧИИ</span>
        <a href="{% url 'add_favourites_item' product.id %}" class="btn">В избранное</a>
    </div>
    {% endif %}
</div>
{% endfor %}
{% endif %}

{% endblock %}